import type { flower } from '../types.js';

export const flowers: flower[] = [
  { name: 'Anise', localized_name: 'アニス' },
  { name: 'Basil', localized_name: 'バジル' },
  { name: 'Cinnamon', localized_name: 'シナモン' },
  { name: 'Dill', localized_name: 'ディル' },
  { name: 'Everlast', localized_name: 'エバーラスト' },
  { name: 'Freesia', localized_name: 'フリージア' },
  { name: 'Gerbera', localized_name: 'ガーベラ' },
  { name: 'Heath', localized_name: 'ヒース' },
  { name: 'Iberis', localized_name: 'イベリス' },
  { name: 'Jasmine', localized_name: 'ジャスミン' },
  { name: 'Kamille', localized_name: 'カモミール' },
  { name: 'Lavender', localized_name: 'ラベンダー' },
  { name: 'Marjoram', localized_name: 'マヨラム' },
  { name: 'Nutmeg', localized_name: 'ナツメグ' },
  { name: 'Oregano', localized_name: 'オレガノ' },
  { name: 'Papyrus', localized_name: 'パピルス' },
  { name: 'Quassia', localized_name: 'クアシア' },
  { name: 'Rosemary', localized_name: 'ローズマリー' },
  { name: 'Saffron', localized_name: 'サフラン' },
  { name: 'Thyme', localized_name: 'タイム' },
  { name: 'Ursinia', localized_name: 'ウルシニア' },
  { name: 'Vanilla', localized_name: 'バニラ' },
  { name: 'Wedelia', localized_name: 'ウェデリア' },
  { name: 'Ximenia', localized_name: 'ハマナツメモドキ' },
  { name: 'Yarrow', localized_name: 'ヤロウ' },
  { name: 'Zedoary', localized_name: 'ゼドアリー' },
];
